export default {
  APP_CREATE_ACCOUNT_SUBMIT: 'APP_CREATE_ACCOUNT_SUBMIT',
  APP_CREATE_ACCOUNT_SUCCESS_RESPONSE: 'APP_CREATE_ACCOUNT_SUCCESS_RESPONSE',
  APP_RESEND_EMAIL: 'APP_RESEND_EMAIL',
  APP_RESEND_EMAIL_SUCCESS: 'APP_RESEND_EMAIL_SUCCESS',
};
